<a href="https://colab.research.google.com/github/bobur-amirov/DataScienceExample/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy ga kirish
Birinchi dars


numpy kutubxonasani chaqirib olish

In [2]:
import numpy as np

Python list bilan numpy kutubxonasidagi massivlar hisoblashlari orasidagi farqni ko'ramiz

In [ ]:
my_list = list(range(100000))  # list
my_array = np.array(range(100000)) #array

In [ ]:
%time for _ in range(10): [i*2 for i in my_list] # list uchun

CPU times: user 91.8 ms, sys: 10.9 ms, total: 103 ms
Wall time: 105 ms


In [ ]:
%time for _ in range(10): my_array*2 # array uchun

CPU times: user 325 µs, sys: 0 ns, total: 325 µs
Wall time: 335 µs


array([     0,      2,      4, ..., 199994, 199996, 199998])

In [ ]:
97.6 / 3.59

27.186629526462394

In [ ]:
arr = np.arange(8).reshape(4,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
arr.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
arr.swapaxes(1,0)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
np.dot(arr, arr.T)

array([[ 1,  3,  5,  7],
       [ 3, 13, 23, 33],
       [ 5, 23, 41, 59],
       [ 7, 33, 59, 85]])

Numpy da shart operatorlaridan foydalanish

In [ ]:
arr1 = np.random.randn(5,5)
arr1

array([[-0.11118373, -0.80920645,  0.64450783, -0.66952143,  0.39027385],
       [-0.14192565, -1.20340497,  1.59286328,  1.18907715, -0.76308741],
       [ 1.45099228,  1.80630137, -1.47948888, -0.34185745, -0.60771853],
       [-0.87667617,  0.82403291,  1.03321259,  0.74847146,  0.26022829],
       [-0.30524182,  0.58349381,  0.48949973,  0.16496256, -0.59950079]])

In [ ]:
result = np.where(arr1<0, -5, 5)
result

array([[-5, -5,  5, -5,  5],
       [-5, -5,  5,  5, -5],
       [ 5,  5, -5, -5, -5],
       [-5,  5,  5,  5,  5],
       [-5,  5,  5,  5, -5]])

Matematik amallar

In [ ]:
arr2 = np.random.randn(5,3)
arr2

array([[-0.01480779,  0.40783169, -0.9721867 ],
       [-1.35130882,  0.18758158,  0.89991866],
       [ 0.3150195 , -0.71526189, -0.45364799],
       [-0.21453638, -1.62197519,  0.02706796],
       [ 0.59835652,  0.7101697 ,  0.8544968 ]])

In [ ]:
arr2.sum()

-1.3432823355231251

In [ ]:
np.sum(arr2)

-1.3432823355231251

In [ ]:
np.sum(arr2, axis=1)

array([-0.5791628 , -0.26380858, -0.85389038, -1.80944361,  2.16302303])

In [ ]:
np.sum(arr2, axis=0)

array([-0.66727697, -1.0316541 ,  0.35564874])

In [ ]:
np.mean(arr2)

-0.08955215570154168

In [4]:
names = np.array(['Sarvar', 'Abdurahmon', 'Hasan',  'Temur', 'Sarvar', 'Temur'])
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [5]:
names

array(['Sarvar', 'Abdurahmon', 'Hasan', 'Temur', 'Sarvar', 'Temur'],
      dtype='<U10')

In [6]:
ints

array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [9]:
ints.sort()
ints

array([1, 1, 2, 2, 3, 3, 3, 4, 4])

In [10]:
np.unique(ints)

array([1, 2, 3, 4])

In [11]:
names1 = np.array(['Jasur', 'Alisher', 'Husan',  'Muhammad', 'Sarvar', 'Temur'])
names2 = np.array(['Sarvar', 'Bahrom', 'Hasan',  'Temur', 'Sarvar', 'Bobur'])

In [12]:
np.setdiff1d(names1, names2)

array(['Alisher', 'Husan', 'Jasur', 'Muhammad'], dtype='<U8')

In [14]:
np.save('names', names1)

In [15]:
np.savez('names12', names1=names1, names2=names2)

In [16]:
names12 = np.load('names12.npz')
names12

In [17]:
names12['names1']

array(['Jasur', 'Alisher', 'Husan', 'Muhammad', 'Sarvar', 'Temur'],
      dtype='<U8')

In [18]:
names12['names2']

array(['Sarvar', 'Bahrom', 'Hasan', 'Temur', 'Sarvar', 'Bobur'],
      dtype='<U6')